import type { Metadata } from "next";
import './globals.css';
import Link from "next/link";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className='py-4 pl-4 text-3xl font-bold bg-slate-400 '>
          <Link href='/'>
            Demo Product Inventory
          </Link>
          <nav className="flex items-center py-4">
                <Link href='/'>                  
                  <div className="mr-10 text-blue-600 hover:text-blue-200 active:text-blue-200">
                    Overview
                  </div>
                </Link>                
                <Link href='/sales'>
                  <div className="mr-10 text-blue-600 hover:text-blue-200">
                    Sales
                  </div>
                </Link>
                <Link href='/new_product'>
                  <div className="mr-10 text-blue-600 hover:text-blue-200">
                    New Product
                  </div>
                </Link>
                <Link href='/new_category'>
                  <div className="mr-10 text-blue-600 hover:text-blue-200">
                    New Category
                  </div>
                </Link>
            </nav>
        </header>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
